In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
import sklearn.linear_model as lm
import matplotlib.pyplot as pl

In [3]:
df=pd.read_excel("Cat_human_New.xlsx")
df.head()

         Color Eye_color  Height  Legs Moustache Tail  Weight  label
0        black     black    5.14     2        No   No    70.0  human
1   dark_brown     brown    6.80     2        No   No    64.4  human
2  light_brown     brown    5.00     2       Yes   No    64.8  human
3  light_brown      blue    5.90     2        No   No    78.8  human
4  light_brown      blue    6.56     2        No   No    73.2  human

In [4]:
import sklearn.preprocessing as pre_process
import numpy as np
ordinal_encoding=pre_process.OrdinalEncoder()
standered_scalling=pre_process.StandardScaler()
one_hot=pre_process.OneHotEncoder()

In [20]:
from sklearn.compose import make_column_transformer #for transforming or encoding multiple features at once
transform_x=make_column_transformer( (one_hot , ['Color','Eye_color','Moustache','Tail'])
,(standered_scalling,['Height','Weight','Legs']))
print(transform_x)

ColumnTransformer(transformers=[('onehotencoder', OneHotEncoder(),
                                 ['Color', 'Eye_color', 'Moustache', 'Tail']),
                                ('standardscaler', StandardScaler(),
                                 ['Height', 'Weight', 'Legs'])])

In [6]:
X=df.iloc[:,0:7]
Y=df.iloc[:,7]
Y.head(4)

0    human
1    human
2    human
3    human
Name: label, dtype: object

In [7]:
processed_x=transform_x.fit_transform(X)

In [9]:
pd.DataFrame(processed_x)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.648913,1.309775,-1.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.302749,1.116700,-1.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.593770,1.130491,-1.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.948260,1.613178,-1.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.208219,1.420103,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,-0.926596,-1.024207,1.0
196,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,-0.828127,-0.907553,1.0
197,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.166862,-0.884222,1.0
198,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,-0.969923,-0.876445,1.0
199,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.048698,-0.832376,1.0

In [22]:
import numpy as np
ordinal_encoder=pre_process.OrdinalEncoder()
processed_y=ordinal_encoder.fit_transform(np.c_[Y])
processed_y

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [11]:
inverse_y = ordinal_encoder.inverse_transform(processed_y)

In [12]:
inverse_y

array([['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat']], dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split( processed_x , processed_y)

In [14]:
import sklearn.svm as sv
model=sv.SVC(kernel='linear')
model.fit(train_x,train_y)

C:\Users\AB\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(kernel='linear')

In [15]:
import sklearn.model_selection as ms
import sklearn.metrics as m
pred_y = ms.cross_val_predict(model, train_x, train_y)
conf_mx = m.confusion_matrix(test_y, pred_y)
conf_mx

C:\Users\AB\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\AB\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\AB\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\AB\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\AB\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ValueError: Found input variables with inconsistent numbers of samples: [50, 150]

In [ ]:
print(m.classification_report(train_y,y_train_pred))

In [ ]:
pred_y=model.predict(test_x)
pred_y

In [ ]:
text_x=pd.DataFrame(test_x)
text_x["true y"]=test_y
text_x["pred_y"]=pred_y

In [ ]:
text_x=pd.DataFrame(test_x)
text_x["test y"]=ordinal_encoder.inverse_transform(test_y)
text_x["pred_y"]=ordinal_encoder.inverse_transform(pred_y.reshape(-1,1))

In [ ]:
pd.DataFrame(test_x)

In [ ]:
try:
    a=int(input("enter num"))
    print("not error")
except:
    print("error")

In [ ]:
from sklearn.utils import all_estimators
estimators = all_estimators(type_filter='classifier')
for name, get_model in estimators:
    try:
         print(name)
    except:
         print('Unable to import', name)

In [ ]:
import sklearn.metrics as sm
from sklearn.utils import all_estimators
estimators = all_estimators(type_filter='classifier')
model_name=[]
model_precision=[]
for name, get_model in estimators:
    try:
        model = get_model()
        model.fit(train_x,train_y)
        pred_y=model.predict(test_x)
        model_precision.append(sm.precision_score(test_y, pred_y))
        model_name.append(name)
    except Exception as e:
        print('Unable to import', name)
        print(e)

In [ ]:
results=pd.DataFrame({"Model Name":model_name , "Model precision":model_precision})
results